line-length = 120
target-version = "py312"

[lint]
select = ["E", "F", "I", "N", "W"]

[lint.per-file-ignores]
"subscribe-incident/test/**/*.py" = ["E402", "E501"]
"negotiation/test/**/*.py" = ["E402", "E501"]
