"""Hypothesis property layer of the negotiation test corpus (port of the Java jqwik ``property`` package).

Five property modules cover design §8.3 — from-data determinism, the from-data round trip, the
error-code partition, the large-parameter merge and the negotiated error paths — each generated by
the strategy port of ``PropertyArbitraries`` over production-wired services (:mod:`.harness`).

The hypothesis profiles are registered in ``conftest.py``: the default profile derandomizes every
run so CI stays byte-deterministic (the D23 counterpart of the Java fixed jqwik seeds); run
``uv run pytest tests/corpus/property --hypothesis-profile=corpus-random`` locally for genuine
random exploration.
"""
